[package]
name = "parabel"
version = "0.0.1"
edition = "2018"
authors = ["Tom Dong <tom.tung.dyb@gmail.com>"]

[dependencies]
bincode = "1.1"
clap = { version = "2.33", optional = true }
hashbrown = "0.5"
itertools = "0.8"
log = "0.4"
ndarray = { version = "0.12", features = ["serde-1"] }
num-traits = "0.2"
order-stat = "0.1"
ordered-float = "1.0"
pbr = "1.0"
rand = "0.7"
rayon = "1.1"
serde = { version = '1.0', features = ['derive'] }
simple_logger = { version = "1.3", optional = true }
sprs = "0.6"
time = "0.1"

[dev-dependencies]
assert_approx_eq = "1.1"

[[bin]]
name = "parabel"
path = "src/bin/parabel.rs"
required-features = ["cli"]

[features]
cli = ["simple_logger", "clap"]
