trigger:
  - master

variables:
  package_name: omikuji
  python.architecture: 'x64'

stages:
  - stage: Rust
    jobs:
      - job: CargoTest
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - template: azure-setup-rust.yml
          - script: |
              set -e -x

              cargo fmt --all -- --check
              cargo test --features cli

              cd c-api
              cargo fmt --all -- --check
              cargo test

  - stage: Python
    jobs:
      - job: SDist
        pool:
          vmImage: 'ubuntu-16.04'
        variables:
          python.version: 3.7
        steps:
          - template: azure-python-build.yml
            parameters:
              sdist: true

      - job: manylinux
        pool:
          vmImage: 'ubuntu-16.04'
        container: 'quay.io/pypa/manylinux2010_x86_64:latest'
        strategy:
          matrix:
            Python3.5:
              python.version: 3.5
            Python3.6:
              python.version: 3.6
            Python3.7:
              python.version: 3.7
        steps:
          - template: azure-python-build.yml
            parameters:
              manylinux: true

      - job: Windows
        pool:
          vmImage: 'vs2017-win2016'
        strategy:
          matrix:
            # Not building for 3.6 & 3.7, because linking fails for some reason ¯\_(ツ)_/¯
            Python3.5:
              python.version: 3.5
        steps:
          - template: azure-python-build.yml

      - job: macOS
        pool:
          vmImage: 'macOS-10.14'
        strategy:
          matrix:
            Python3.5:
              python.version: 3.5
            Python3.6:
              python.version: 3.6
            Python3.7:
              python.version: 3.7
        steps:
          - template: azure-python-build.yml
