[package]
name = "omikuji_c-api"
version = "0.3.1"
edition = "2018"
authors = ["Tom Dong <tom.tung.dyb@gmail.com>"]

[lib]
name = "omikuji"
crate-type = ["staticlib", "cdylib"]

[dependencies]
itertools = "0.9.*"
libc = "0.2.*"
omikuji = { path = ".." }
simple_logger = "1.6.*"

[build-dependencies]
cbindgen = "0.14.*"

[profile.release]
panic = "abort"
