[package]
name = "omikuji_c-api"
version = "0.3.1"
edition = "2018"
authors = ["Tom Dong <tom.tung.dyb@gmail.com>"]

[lib]
name = "omikuji"
crate-type = ["staticlib", "cdylib"]

[dependencies]
itertools = "0.8"
libc = "0.2"
omikuji = { path = ".." }
rayon = "1.2"
simple_logger = "1.3"

[build-dependencies]
cbindgen = "0.11"

[profile.release]
panic = "abort"
